### ISSUE TITLE
Arduino Library "more info" link broken

### ISSUE THREAD

**Issue by neocogent** [PRosenb/SPIFFS_FilePrint#2]
As above, the "more info" link in the Arduino Library Manager is missing the first S in SPIFFS_FilePrint so if clicked it goes to missing page in github.

Just thought you'd like to know.

**Comment by PRosenb** [comment]
Many thanks for letting me know. It was in fact fixed long time ago but never released. I  just released it now, hopefully it will be fine soon. Cheers
